Publish docker images for PR jobs to the parent fork.
youtube/cobalt_sandbox pull request #149
Opened 2022-12-23 01:23 UTC by isarkis

2022-12-29 18:26 UTC, isarkis commented
This PR can only be pushed after we build new linux runner (see cl/498104088 and http://go/lbreview/239040)

2023-01-04 18:46 UTC, andrewsavage1 requested changes

2023-01-04 18:46 UTC, andrewsavage1 commented on .github/actions/docker/action.yaml
> +      if: ${{ (steps.changed-files.outputs.any_changed == 'false') && (github.event_name == 'pull_request') && (github.repository == github.event.pull_request.head.repo.full_name) }}
I believe you can just use the boolean `github.event.pull_request.head.repo.fork`

2023-01-04 18:46 UTC, andrewsavage1 commented on .github/actions/docker/action.yaml
> +      if: ${{ (steps.changed-files.outputs.any_changed == 'true') && (github.event_name == 'pull_request') && (github.repository != github.event.pull_request.head.repo.full_name) }}
Same as above

2023-01-04 18:46 UTC, andrewsavage1 commented on .github/actions/docker_win/action.yaml
> +      if: ${{ (env.need_to_build == 'true') && ((github.event_name != 'pull_request') || (github.repository == github.event.pull_request.head.repo.full_name)) }}
Same as above

2023-01-04 18:46 UTC, andrewsavage1 commented on .github/actions/docker_win/action.yaml
> +      if: ${{ (env.need_to_build == 'true') && ((github.event_name != 'pull_request') || (github.repository == github.event.pull_request.head.repo.full_name)) }}
Same as above

2023-01-04 19:06 UTC, andrewsavage1 requested changes

2023-01-04 19:06 UTC, andrewsavage1 commented on .github/actions/docker/action.yaml
> +      if: ${{ (steps.changed-files.outputs.any_changed == 'true') (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.fork) }}
Missing an "and" or "or"

2023-01-04 21:48 UTC, andrewsavage1 approved these changes

2023-01-04 21:59 UTC, merged